# -*- coding: utf-8 -*-
"""Organizador de festas com Agentes de IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLVlcON_69uXOVeZ3QJ1s8ODKC-V3sit
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()
# para consultar outras opções de modelo
# for model in client.models.list():
#   print(model.name)
MODEL_SIMPLES = "gemini-2.0-flash"
MODEL_COMPLETO = "gemini-2.5-pro-exp-03-25"

# Instalar Framework de agentes do Google ################################################
!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import json
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Stakeholder --- #
##########################################
def agente_cliente(tipo_evento):

    cliente = Agent(
        name="agente_cliente",
        model=MODEL_SIMPLES,
        instruction="""
        Você é um cliente de uma empresa que organiza eventos, sendo assim você cria um evento específico como uma festa de casamento, aniversário ou team building.
        Para criar um evento, você deve indicar de forma aleatoria uma data futura de até um mês a frente, qual o horário e uma quantidade de convidados.
        O tipo de evento será informado a seguir.
        """,
        description="Agente que cria uma demanda para uma equipe de desenvolvimento"
    )

    entrada_do_agente_cliente = f"Problema principal: {tipo_evento}"

    detalhes_evento = call_agent(cliente, entrada_do_agente_cliente)
    return detalhes_evento

### teste do agente cliente
# tipo_evento = "Casamento no Porto"
# detalhes_evento = agente_cliente(tipo_evento)
# print("\n--- 📝 Resultado do cliente ---\n")
# display(to_markdown(detalhes_evento))

################################################
# --- Agente 2: Auxiliar Administrativo --- #
################################################
def agente_aux_adm(tipo_evento, detalhes_evento):
    aux_adm = Agent(
        name="agente_aux_adm",
        model=MODEL_SIMPLES,
        instruction="""
        Você é um auxiliar administrativo de uma empresa que organiza diversos tipos de eventos e é responsável por receber os pedidos dos clientes.
        Sua função vai ser consultar na internet através da ferramenta de busca do google (google_search) para descobrir o que é necessário para o evento acontecer.
        Exemplos do que deve ser levado em conta para isso:
        - festas de casamentos precisam de um local com salão grande ou que seja open space, mesas e cadeiras, decoração com flores, um bolo de casamento, aperetivos, bebidas alcoolicas e não-alcoolicas, e um DJ.
        - festas de aniversários para menores de idades precisam de um local fechado, mesas e cadeiras, bolo de aniversário, aperetivos, bebidas não-alcoolicas e um DJ.
        - team building precisam de um local open space, mesas e cadeira, aperetivos, bebidas alcoolicas e não-alcoolicas.

        Devolva a resposta em formato que pode ser utilizado com array do python e a saída deve conter estritamente apenas a estrutura de dados do python e que siga o JSON schema a seguir

        {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Evento de Casamento",
          "description": "Schema para descrever detalhes de um evento de casamento, incluindo elementos essenciais.",
          "type": "object",
          "properties": {
            "Tipo de Evento": {
              "type": "string",
              "description": "O tipo do evento, por exemplo, 'Casamento'."
            },
            "Localização": {
              "type": "string",
              "description": "A localização do evento (cidade e país)."
            },
            "Data": {
              "type": "string",
              "description": "A data do evento."
            },
            "Horário": {
              "type": "string",
              "description": "O horário do evento."
            },
            "Número de Convidados": {
              "type": "integer",
              "description": "O número estimado de convidados."
              // Podemos adicionar "minimum": 0 se for o caso, mas para este exemplo não é estritamente necessário com base nos dados fornecidos.
            },
            "Elementos Essenciais": {
              "type": "array",
              "description": "Uma lista dos elementos essenciais necessários para o evento.",
              "items": {
                "type": "object",
                "properties": {
                  "Categoria": {
                    "type": "string",
                    "description": "A categoria do elemento essencial (ex: 'Local/Espaço para Casamento', 'Catering')."
                  },
                  "Necessidades": {
                    "type": "array",
                    "description": "Uma lista de necessidades ou opções específicas dentro desta categoria.",
                    "items": {
                      "type": "string",
                      "description": "Uma descrição individual de uma necessidade ou opção."
                    }
                  }
                },
                "required": [
                  "Categoria",
                  "Necessidades"
                ]
              }
            }
          },
          "required": [
            "Tipo de Evento",
            "Localização",
            "Data",
            "Horário",
            "Número de Convidados",
            "Elementos Essenciais"
          ]
        }
        """,
        description="Agente que busca o que precisa ",
        tools=[google_search]
    )

    entrada_do_agente_aux_adm = f"Tipo de evento: {tipo_evento}\nDetalhes do evento: {detalhes_evento}"
    # Executa o agente
    plano_evento = call_agent(aux_adm, entrada_do_agente_aux_adm)
    return plano_evento

### teste o agente auxiliar administrativo
# plano_evento = agente_aux_adm(tipo_evento, detalhes_evento)
# print("\n--- 📝 Resultado do auxiliar administrativo ---\n")
# display(to_markdown(plano_evento))

######################################
# --- Agente 3: Analista de orçamentos --- #
######################################
def agente_analista_budget(tipo_evento, categoria, elemento_essencial):
    analista_budget = Agent(
        name="agente_analista_budget",
        model=MODEL_SIMPLES,
        instruction="""
        Você é um analista de orçamentos especializado em uma categoria específica, como fazer orçamento para alugar locais ou orçamento para catering ou orçamento para contratar uma banda.
        Sua função vai ser consultar na internet através da ferramenta de busca do google (google_search) para atender aos elementos essenciais do tipo de evento que lhe foram informados.
        Busque 5 opções de orçamento para a sua categoria e escolha as 3 opções mais baratas.

        Devolva a resposta em formato que pode ser utilizado com array do python e a saída deve conter estritamente apenas a estrutura de dados do python e que siga o JSON schema a seguir
        {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Lista de Opções",
          "description": "Schema para uma lista de opções, cada uma com nome, preço e características.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Opção": {
                "type": "string",
                "description": "O nome ou título da opção."
              },
              "Preço": {
                "type": "string",
                "description": "Informação sobre o preço da opção."
              },
              "Características": {
                "type": "array",
                "description": "Uma lista de características associadas a esta opção.",
                "items": {
                  "type": "string",
                  "description": "Uma descrição individual de uma característica."
                }
              }
            },
            "required": [
              "Opção",
              "Preço",
              "Características"
            ]
          }
        }
        """,
        description="Agente que atua como analista de orçamentos",
        tools=[google_search]
    )
    entrada_do_agente_analista_budget = f"Tipo de evento: {tipo_evento}\nCategoria Orçamento: {categoria}\nElemento essencial: {elemento_essencial}"
    # Executa o agente
    rascunho = call_agent(analista_budget, entrada_do_agente_analista_budget)
    return rascunho

### teste o agente analista de orçamento
# import json
# plano_object = json.loads(plano_evento.replace("```json", "").replace("```", ""))
# budget = agente_analista_budget(tipo_evento, plano_object.get("Elementos Essenciais")[0].get("Categoria"), plano_object.get("Elementos Essenciais")[0].get("Necessidades"))
# print("\n--- 📝 Resultado do analista de orçamento ---\n")
# display(to_markdown(budget))

##########################################
# --- Agente 4: Organizador do evento --- #
##########################################

def agente_organizador(tipo_evento, budgets):
    organizador = Agent(
        name="agente_organizador",
        model=MODEL_SIMPLES,
        instruction="""
        Você é o organizador de um evento.
        Sua função inicial será analisar os orçamentos recebidos (budgets) de diversas categorias e montar 3 planos bastante resumidos para apresentar ao cliente, citando o principalmente o valor de cada um deles.
        """,
        description="Agente organizador.",
    )
    entrada_do_agente_organizador = f"Tipo de evento: {tipo_evento}\Lista de Orçamentos: {budgets}\n"
    # Executa o agente
    evento = call_agent(organizador, entrada_do_agente_organizador)
    return evento

def agente_atendente(tipo_evento, evento, msg):
    atendente = Agent(
        name="agente_atendente",
        model=MODEL_SIMPLES,
        instruction="""
        Você é um atendente de um evento e irá conversar com o cliente sobre o evento informado.
        Você irá receber um plano de evento (evento) e uma resposta do cliente (msg) e sempre deixará uma pergunta para o cliente até que ele confirme que está satisfeito com o evento.
        """,
        description="Agente atendente.",
    )
    entrada_do_agente_atendente = f"Tipo de evento: {tipo_evento}\Evento: {evento}\nResposta do cliente"
    # Executa o agente
    resposta_atendente = call_agent(atendente, entrada_do_agente_atendente)
    return resposta_atendente

### teste o agente analista de orçamento
# plano_object = json.loads(plano_evento.replace("```json", "").replace("```", ""))
# budgets = []
# for elemento_essencial in plano_object.get("Elementos Essenciais"):
#   budget = agente_analista_budget(tipo_evento, elemento_essencial.get("Categoria"), elemento_essencial.get("Necessidades"))
#   budgets.append(budget)
# evento = agente_organizador(tipo_evento, budgets)
# print("\n--- 📝 Resultado do organizador do evento ---\n")
# display(to_markdown(evento))

def remover_conteudo_ate_substring(texto_completo, marcador_substring):
  """
  Remove o conteúdo de uma string até encontrar um marcador_substring.

  Args:
    texto_completo: A string original.
    marcador_substring: A substring que marca o ponto a partir do qual
                        o conteúdo deve ser mantido.

  Returns:
    A parte da string original após o marcador_substring (incluindo o marcador,
    se quiseres manter a partir dele, ou excluindo-o, como no exemplo).
    Se o marcador não for encontrado, devolve a string original.
  """
  posicao_marcador = texto_completo.find(marcador_substring)

  # Verifica se o marcador foi encontrado
  if posicao_marcador != -1:
    # Calcula a posição onde a substring marcador termina
    fim_marcador = posicao_marcador + len(marcador_substring)
    # Retorna a parte da string após o marcador
    return texto_completo[fim_marcador:]
  else:
    # Se o marcador não for encontrado, retorna a string original
    # print(f"Atenção: O marcador '{marcador_substring}' não foi encontrado na string.")
    return texto_completo

print("🚀 Iniciando o Sistema de Criação de MVP com 4 Agentes 🚀")

# --- Obter o Tópico do Usuário ---
tipo_evento = input("Olá, somos a Kreyzon Events, em que tipo de evento podemos ajudar? ")

# Inserir lógica do sistema de agentes ################################################
if not tipo_evento:
    print("Você esqueceu de digitar o que quer!")
else:
    print(f"Maravilha! Vou falar com a equipe para lhe dar as melhores opções para seu evento.")

    detalhes_evento = agente_cliente(tipo_evento)
    # trace flow
    # print("\n--- 📝 Resultado do cliente ---\n")
    # display(to_markdown(detalhes_evento))
    # print("--------------------------------------------------------------")

    plano_evento = agente_aux_adm(tipo_evento, detalhes_evento)
    # trace flow
    # print("\n--- 📝 Resultado do Product Owner ---\n")
    # display(to_markdown(plano_evento))
    # print("--------------------------------------------------------------")

    # criação
    plano_object = json.loads(remover_conteudo_ate_substring(plano_evento, "```json").replace("```json", "").replace("```", ""))
    budgets = []
    for elemento_essencial in plano_object.get("Elementos Essenciais"):
      budget = agente_analista_budget(tipo_evento, elemento_essencial.get("Categoria"), elemento_essencial.get("Necessidades"))
      budgets.append(budget)

    # trace flow
    # print("\n--- 📝 Resultado do Scrum Master ---\n")
    # display(to_markdown(rascunho_de_post))
    # print("--------------------------------------------------------------")

    evento = agente_organizador(tipo_evento, budgets)
    print("\n--- 📝 Resultado do Evento ---\n")
    display(to_markdown(evento))
    print("--------------------------------------------------------------")

msg = input("Você gostou de alguma das opções ou tem alguma dúvida sobre o evento? ")
    while msg != 'fim':
        resposta_atendente = agente_atendente(tipo_evento, evento, msg)
        display(to_markdown(resposta_atendente))
        print("--------------------------------------------------------------")
        msg = input()
